name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Creating GitHub Organization Repository
        run: |
          gh repo create my-new-project --template AlicTheScreaminCat/infrastructure-repo-template --private --clone
          ls -ltrh
      #  with:
      #    org-admin-token: '${{ secrets.ORG_ADMIN_TOKEN }}'
      # - name: Log URL to the repo
      #   run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"
      